seed_everything: 42
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: qmean-net-gin-regressor
      save_dir: _checkpoints
      version: null
      offline: false
      dir: null
      id: null
      anonymous: null
      project: QmeanNet
      log_model: false
      experiment: null
      prefix: ''
      checkpoint_name: null
      add_file_policy: mutable
      entity: neurone-lab
      notes: null
      tags: [gnn, gin]
      config: null
      config_exclude_keys: null
      config_include_keys: null
      allow_val_change: null
      group: null
      job_type: null
      mode: null
      force: null
      reinit: null
      resume: null
      resume_from: null
      fork_from: null
      save_code: null
      tensorboard: null
      sync_tensorboard: null
      monitor_gym: null
      settings: null
  callbacks:
  - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    init_args:
      logging_interval: epoch
      log_momentum: false
      log_weight_decay: false
  - class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      monitor: val/loss
      min_delta: 0.0
      patience: 25
      verbose: true
      mode: min
      strict: true
      check_finite: true
      stopping_threshold: null
      divergence_threshold: null
      check_on_train_epoch_end: false
      log_rank_zero_only: false
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: _checkpoints
      filename: qmean-net-gcn-regressor-{epoch:02d}-{val_loss:.2f}
      monitor: val/loss
      verbose: true
      save_last: null
      save_top_k: 1
      save_on_exception: false
      save_weights_only: false
      mode: min
      auto_insert_metric_name: true
      every_n_train_steps: null
      train_time_interval: null
      every_n_epochs: null
      save_on_train_epoch_end: true
      enable_version_counter: true
  fast_dev_run: false
  max_epochs: 100
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: _checkpoints
  enable_autolog_hparams: true
  model_registry: null

model:
  lr: 0.001
  weight_decay: 0.0001
  model_name: Rostlab/prot_bert
  dropout_rate: 0.3
  n_regressor_layers: 2
  use_gnn: GIN
  gnn_in_channels: 11
  gnn_hidden_dim: 128
  gnn_num_layers: 2
data:
  root: smiles
  target_csv: qmean_global_scores_clean.csv
  batch_size: 32
  num_workers: 8
  train_fraction: 0.8
  val_fraction: 0.1
  test_fraction: 0.1
  seed: 42
optimizer: null
lr_scheduler: null
ckpt_path: null
weights_only: null
